---

- name: 'install required packages'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - ufw
    - fail2ban
    - unattended-upgrades
    - logwatch
    - sendmail-bin 
    - sendmail
  tags: [ 'packages' ]

- name: 'set the timezone for the server to be UTC'
  file:
    src: /usr/share/zoneinfo/Europe/Berlin
    dest: /etc/localtime
    state: link
    force: no
  register: timezone

- name: 'reconfigure timezone data'
  shell: dpkg-reconfigure -f noninteractive tzdata
  when: timezone.changed
  
- name: 'set up a unique hostname'
  hostname:
    name: '{{ local_hostname }}'
  when: "'minecraft' in group_names"
  with_items: "{{ groups['minecraft'] }}"

- name: "add the server's domain to the hosts file"
  lineinfile:
    path: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ local_fqdn_name }} {{ local_hostname }}"
    state: present
  when: "'minecraft' in group_names and hostvars[item].ansible_default_ipv4.address is defined"
  with_items: "{{ groups['minecraft'] }}"

- name: 'adjust APT update intervals'
  copy:
    src: apt_periodic 
    dest: /etc/apt/apt.conf.d/10periodic

- name: 'configure a firewall'
  block:
  - name: 'setup ufw'
    ufw: 
      state: enabled 
      policy: deny
 
  - name: 'allow ssh traffic'
    ufw:
      rule: allow 
      port: '{{ common_ssh_port }}' 
      proto: tcp

  - name: 'allow mosh traffic'
    ufw:
      rule: allow 
      proto: udp 
      port: '{{ common_mosh_from_port }}:{{ common_mosh_to_port }}'

- name: 'configure logwatch'
  block: 
  - name: 'set up Postfix to relay mail'
    debconf:
      name: postfix
      question: '{{ item.question }}'
      value: '{{ item.value }}'
      vtype: '{{ item.vtype }}'
    with_items:
      - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
      - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }
  
  - name: 'email log summary daily'
    lineinfile:
      path: /etc/cron.daily/00logwatch
      regexp: "^/usr/sbin/logwatch"
      line: "/usr/sbin/logwatch --output mail --mailto {{ common_logwatch_email }} --detail high"
      state: present 
      create: yes

- name: 'lockdown ssh access'
  block:
  - name: 'change ssh port'
    lineinfile: 
      path: /etc/ssh/sshd_config
      regexp: '^Port\s'
      line: 'Port {{ common_ssh_port }}'
      state: present
    notify: restart ssh
  
  - name: 'disallow password authentication'
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
      state: present
    notify: restart ssh
  
  - name: 'disallow root SSH access'
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
      state: present
    notify: restart ssh

  - name: 'listen on only one internet protocol - IPv4'
    lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: EOF
      line: 'AddressFamily inet'
      state: present
    notify: restart ssh
    
  when: "'minecraft' in group_names"

- name: 'upgrade all packages to the latest version'
  apt:
    name: "*"
    state: latest
  tags: [ 'packages' ]
