---

- name: 'update apt cache'
  apt:
    update_cache: yes
    cache_valid_time: 86400
  tags: [ 'packages' ]

- name: 'install required packages'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - sudo
    - aptitude
  tags: [ 'packages' ]
